//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_userAnswers
    {
        public int userAnswerId { get; set; }
        public long answerId { get; set; }
        public int userId { get; set; }
    
        public virtual tb_answers tb_answers { get; set; }
        public virtual tb_users tb_users { get; set; }
    }
}
